# This worflow runs once to initialize repository
# In particular, it will replace assetPath with the repositiory name, in order toserve assets correctly.
# Possibly one day Gatsby implements relative pathes, and this step can be skipped
# details: https://github.com/gatsbyjs/gatsby/discussions/14161

name: Init

# Controls when the workflow will run
on: 
 push:
    branches:
      - main
jobs:
  replace-path:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, 'Initial commit')"
    steps:
      - run: echo ${{github.event}}
      - uses: actions/checkout@v2
        with:
          ref: gh-pages

      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@v1
        with:
          find: "/tool-starter"
          replace: /${{github.event.repository.name}}
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Replace asset prefix with repository name
          skip_dirty_check: true    
          skip_fetch: true    
          disable_globbing: true
     
          
  remove-workflow:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, 'Initial commit')"
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main

      - name: Remove workflow
        run: rm .github/workflows/init.yml
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Remove init workflow
          

